#!/usr/bin/env node

import { parseArgs } from 'node:util';
import { createInterface } from 'node:readline';
import fs from 'fs';
import generateExports from './generate-exports.mjs';

const { values } = parseArgs({
  args: process.argv.slice(2),
  options: {
    refresh: { type: 'boolean', short: 'r' },
    help: { type: 'boolean', short: 'h' },
    yes: { type: 'boolean', short: 'y' },
  },
});

if (values.help) {
  console.log(`
openbridge-helper CLI

Usage:
  npx openbridge-helper              Generate OpenBridge exports (if not already generated)
  npx openbridge-helper --refresh    Force regenerate exports
  npx openbridge-helper --yes        Skip prompts and apply all config changes
  npx openbridge-helper --help       Show this help

Examples:
  npx openbridge-helper
  npx openbridge-helper -r
  npx openbridge-helper -y
`);
  process.exit(0);
}

// Prompt helper
function ask(question) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.toLowerCase().startsWith('y'));
    });
  });
}

// Check if exports are already generated
function areExportsGenerated() {
  const file = 'src/utils/openbridge-helper/index.ts';

  if (!fs.existsSync(file)) {
    return false;
  }

  const content = fs.readFileSync(file, 'utf8');

  // Check for the generated file header and actual exports
  const hasHeader = content.includes('// Generated by openbridge-helper');
  const hasExports = content.includes('export { Obc') || content.includes('export { Obi');

  return hasHeader && hasExports;
}

if (areExportsGenerated() && !values.refresh) {
  console.error(`
OpenBridge exports are already generated.

If you want to regenerate (e.g., after updating OpenBridge), use:
  npx openbridge-helper --refresh

Or manually delete src/utils/openbridge-helper/ and run again.
`);
  process.exit(1);
}

try {
  await generateExports();
  console.log('OpenBridge exports generated successfully!\n');

  // --- .gitignore ---
  const gitignorePath = '.gitignore';
  const gitignoreEntry = 'src/utils/openbridge-helper/';
  let gitignoreContent = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, 'utf8') : '';

  if (!gitignoreContent.includes(gitignoreEntry)) {
    const shouldAdd = values.yes || await ask(`Add "${gitignoreEntry}" to .gitignore? [Y/n] `);
    if (shouldAdd) {
      const comment = '\n# Generated by openbridge-helper\n';
      fs.appendFileSync(gitignorePath, comment + gitignoreEntry + '\n');
      console.log('Added to .gitignore\n');
    }
  }

  // --- tsconfig.app.json ---
  const tsconfigPath = 'tsconfig.app.json';
  if (fs.existsSync(tsconfigPath)) {
    const tsconfig = JSON.parse(fs.readFileSync(tsconfigPath, 'utf8'));
    if (!tsconfig.compilerOptions) tsconfig.compilerOptions = {};
    if (!tsconfig.compilerOptions.paths) tsconfig.compilerOptions.paths = {};

    if (!tsconfig.compilerOptions.paths['openbridge-helper']) {
      const shouldAdd = values.yes || await ask(`Add path alias to ${tsconfigPath}? [Y/n] `);
      if (shouldAdd) {
        tsconfig.compilerOptions.paths['openbridge-helper'] = ['./src/utils/openbridge-helper'];
        fs.writeFileSync(tsconfigPath, JSON.stringify(tsconfig, null, 2) + '\n');
        console.log('Added path alias to tsconfig.app.json\n');
      }
    }
  }

  // --- vite.config.ts ---
  const viteConfigPath = 'vite.config.ts';
  if (fs.existsSync(viteConfigPath)) {
    let viteContent = fs.readFileSync(viteConfigPath, 'utf8');

    if (!viteContent.includes('"openbridge-helper"') && !viteContent.includes("'openbridge-helper'")) {
      const shouldAdd = values.yes || await ask(`Add resolve alias to ${viteConfigPath}? [Y/n] `);

      if (shouldAdd) {
        // Add import if not present
        if (!viteContent.includes('fileURLToPath')) {
          viteContent = viteContent.replace(
            /^(import .+ from ['"]vite['"];?\n)/m,
            '$1import { fileURLToPath, URL } from "node:url";\n'
          );
        }

        // Add resolve.alias block
        const aliasBlock = `resolve: {
    alias: {
      "openbridge-helper": fileURLToPath(
        new URL("./src/utils/openbridge-helper/index.ts", import.meta.url)
      ),
    },
  },`;

        if (viteContent.includes('resolve:')) {
          // Add to existing resolve.alias
          if (viteContent.includes('alias:')) {
            viteContent = viteContent.replace(
              /alias:\s*\{/,
              `alias: {\n      "openbridge-helper": fileURLToPath(\n        new URL("./src/utils/openbridge-helper/index.ts", import.meta.url)\n      ),`
            );
          } else {
            viteContent = viteContent.replace(
              /resolve:\s*\{/,
              `resolve: {\n    alias: {\n      "openbridge-helper": fileURLToPath(\n        new URL("./src/utils/openbridge-helper/index.ts", import.meta.url)\n      ),\n    },`
            );
          }
        } else {
          // Add resolve block after plugins or at end of defineConfig
          if (viteContent.includes('plugins:')) {
            viteContent = viteContent.replace(
              /(plugins:\s*\[[^\]]*\],?)/,
              `$1\n  ${aliasBlock}`
            );
          } else {
            viteContent = viteContent.replace(
              /defineConfig\(\{/,
              `defineConfig({\n  ${aliasBlock}`
            );
          }
        }

        fs.writeFileSync(viteConfigPath, viteContent);
        console.log('Added resolve alias to vite.config.ts\n');
      } else {
        // Show instructions if user declined
        console.log(`
To use the "openbridge-helper" import alias, add the following to your vite.config.ts:

1. Add this import at the top of the file:

   import { fileURLToPath, URL } from "node:url";

2. Add this inside defineConfig (create resolve.alias if it doesn't exist):

   resolve: {
     alias: {
       "openbridge-helper": fileURLToPath(
         new URL("./src/utils/openbridge-helper/index.ts", import.meta.url)
       ),
     },
   },
`);
      }
    }
  }

  console.log('Done! You can now import from "openbridge-helper"');

} catch (error) {
  console.error('Error:', error.message);
  process.exit(1);
}
