#!/usr/bin/env node

import { parseArgs } from 'node:util';
import fs from 'fs';
import generateExports from './generate-exports.mjs';

const { values } = parseArgs({
  args: process.argv.slice(2),
  options: {
    refresh: { type: 'boolean', short: 'r' },
    help: { type: 'boolean', short: 'h' },
  },
});

if (values.help) {
  console.log(`
openbridge-helper CLI

Usage:
  npx openbridge-helper              Generate OpenBridge exports (if not already generated)
  npx openbridge-helper --refresh     Force regenerate exports
  npx openbridge-helper --help        Show this help

Examples:
  npx openbridge-helper
  npx openbridge-helper -r
`);
  process.exit(0);
}

// Check if exports are already generated
function areExportsGenerated() {
  const file = 'src/openbridge-helper.ts';

  if (!fs.existsSync(file)) {
    return false;
  }

  const content = fs.readFileSync(file, 'utf8');

  // Check if more than placeholder
  const hasIcons = content.includes('export { Obi') && !content.includes('Placeholder');
  const hasComps = content.includes('export { Obc') && !content.includes('Placeholder');

  return hasIcons || hasComps;
}

if (areExportsGenerated() && !values.refresh) {
  console.error(`
❌ OpenBridge exports are already generated.

If you want to regenerate (e.g., after updating OpenBridge), use:
  npx openbridge-helper --refresh

Or manually delete src/openbridge-helper.ts and run again.
`);
  process.exit(1);
}

try {
  await generateExports();
  console.log('✅ OpenBridge exports generated successfully!');

  // Add to .gitignore if not already present
  const gitignorePath = '.gitignore';
  const entry = 'src/openbridge-helper.ts';
  let gitignoreContent = '';
  if (fs.existsSync(gitignorePath)) {
    gitignoreContent = fs.readFileSync(gitignorePath, 'utf8');
  }
  if (!gitignoreContent.includes(entry)) {
    const comment = '\n# Generated by openbridge-helper\n';
    fs.appendFileSync(gitignorePath, comment + entry + '\n');
    console.log('✅ Added src/openbridge-helper.ts to .gitignore');
  }

  // Add path alias to tsconfig.json if it exists
  const tsconfigPath = 'tsconfig.app.json';
  if (fs.existsSync(tsconfigPath)) {
    const tsconfig = JSON.parse(fs.readFileSync(tsconfigPath, 'utf8'));
    if (!tsconfig.compilerOptions) tsconfig.compilerOptions = {};
    if (!tsconfig.compilerOptions.paths) tsconfig.compilerOptions.paths = {};
    if (!tsconfig.compilerOptions.paths['openbridge-helper']) {
      tsconfig.compilerOptions.paths['openbridge-helper'] = ['./src/openbridge-helper.ts'];
      fs.writeFileSync(tsconfigPath, JSON.stringify(tsconfig, null, 2));
      console.log('✅ Added path alias for "openbridge-helper" to tsconfig.json');
    }
  }
} catch (error) {
  console.error('❌ Error:', error.message);
  process.exit(1);
}